#!/usr/bin/expect

# setup
set timeout 1
expect_before {
    timeout { puts "FAILED: timeout"; exit 2 }
    eof     { puts "FAILED: eof";     exit 1 }
}

# start
spawn ./rdb
expect "db>"

# suppress output
log_user 0

# test table mux row is 1400
for {set i 1} {$i<=1400} {incr i} {
  send "insert $i foo bar$i\r"
  expect "Executed."
}
log_user 1
send "insert 1401 foo bar1401\r"
expect "Error: Table full."

puts "*** SUCCESS - 2 ***"
